### PR TITLE
Universocraft Skywars and BedWars AutoPlay

### PR DESCRIPTION
**Pull request by cranci1**
Working fine for both! 

Its just a simple integration I'm to lazy to add a menu to choose bedwars or skywars mode so there are 2 modes.

### CODE REVIEW

**Comment by toidicakhia** [comment]
That's good, but we want to remap command with minigames

Example: 
- bedwars -> bedwars random
- skywars, luckywars -> skywars random

> Working fine for both!
> 
> Its just a simple integration I'm to lazy to add a menu to choose bedwars or skywars mode so there are 2 modes.

**Comment by toidicakhia** [comment]
@longathelstan can you remap it?

> That's good, but we want to remap command with minigames
> 
> Example:
> 
> * bedwars -> bedwars random
> * skywars, luckywars -> skywars random
> 
> > Working fine for both!
> > Its just a simple integration I'm to lazy to add a menu to choose bedwars or skywars mode so there are 2 modes.

@longathelstan can you remap it?

**Comment by longathelstan** [comment]
> @longathelstan can you remap it?
> 
> > That's good, but we want to remap command with minigames
> > Example:
> > 
> > * bedwars -> bedwars random
> > * skywars, luckywars -> skywars random
> > 
> > > Working fine for both!
> > > Its just a simple integration I'm to lazy to add a menu to choose bedwars or skywars mode so there are 2 modes.

ok

**Review by toidicakhia — COMMENTED** [review]
Updated new method to auto play, verify that it works.

**Comment by cranci1** [comment]
> Updated new method to auto play, pls verify that it works.

Everything works fine, thanks

**Review by toidicakhia — APPROVED** [review]

**Pull request merged**
